# Generated by Django 4.2.6 on 2023-10-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='merchandise', verbose_name='Photo')),
                ('is_main', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Disposal',
                'verbose_name_plural': 'Disposal',
            },
        ),
    ]
