# Generated by Django 4.2.6 on 2023-10-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposal',
            name='likes',
        ),
    ]
